"""Unit tests for toolbox.logger without requiring ArcGIS Pro."""

from __future__ import annotations

import unittest
from pathlib import Path
from unittest.mock import patch

from toolbox import logger


class _FakeArcPy:
    """Capture ArcGIS message calls made by Logger."""

    def __init__(self) -> None:
        self.calls = []

    def AddMessage(self, message: str) -> None:
        self.calls.append(("INFO", message))

    def AddWarning(self, message: str) -> None:
        self.calls.append(("WARNING", message))

    def AddError(self, message: str) -> None:
        self.calls.append(("ERROR", message))


class LoggerTests(unittest.TestCase):
    """Verify file output, levels, ArcPy routing, and diagnostics."""

    def setUp(self) -> None:
        """Create a deterministic workspace-local output folder for each test."""
        self.output_folder = Path(__file__).parent / "_test_output" / self._testMethodName
        self.output_folder.mkdir(parents=True, exist_ok=True)

    def tearDown(self) -> None:
        """Remove only the test log generated by the current test."""
        log_path = self.output_folder / "Migration.log"
        if log_path.exists():
            log_path.unlink()
        self.output_folder.rmdir()

    def test_writes_all_levels_and_routes_arcgis_messages(self) -> None:
        """Logger writes timestamped output and sends expected ArcPy calls."""
        fake_arcpy = _FakeArcPy()
        with patch.object(logger, "arcpy", fake_arcpy):
            instance = logger.Logger(str(self.output_folder))
            log_path = Path(instance.initialize())
            instance.info("information")
            instance.warning("warning")
            instance.error("error")
            instance.critical("critical")
            instance.section("Migration")
            instance.separator()
            instance.statistics("Counts", {"Read": 2, "Migrated": 1})
            try:
                raise ValueError("bad mapping")
            except ValueError as error:
                instance.exception(error, "Validation")
            instance.close()

            content = log_path.read_text(encoding="utf-8")
            self.assertEqual(log_path.name, "Migration.log")
            for level in ("INFO", "WARNING", "ERROR", "CRITICAL"):
                self.assertIn(level, content)
            self.assertIn("Traceback", content)
            self.assertIn("Execution time", content)
            self.assertEqual([item[0] for item in fake_arcpy.calls[:4]], ["INFO", "WARNING", "ERROR", "ERROR"])

    def test_context_manager_logs_unhandled_exception_without_suppressing_it(self) -> None:
        """Logger records context exceptions and allows callers to handle them."""
        instance = logger.Logger(str(self.output_folder), write_to_arcpy=False)
        with self.assertRaises(RuntimeError):
            with instance:
                raise RuntimeError("stop")
        content = Path(instance.log_path).read_text(encoding="utf-8")
        self.assertIn("Unhandled exception", content)
        self.assertIn("RuntimeError: stop", content)


if __name__ == "__main__":
    unittest.main()
